export const GameViewId = {
    SELECT_ELEMENT_1: "SELECT_ELEMENT_1",
    SELECT_ELEMENT_2: "SELECT_ELEMENT_2",
    SELECT_ELEMENT_ADDITION: "SELECT_ELEMENT_ADDITION",
    SELECT_ELEMENT_EQUAL: "SELECT_ELEMENT_EQUAL",
    SELECT_ELEMENT_QUESTION: "SELECT_ELEMENT_QUESTION",
    FORMULA_AND_DISCOVER_AREA: "FORMULA_AND_DISCOVER_AREA",
    FORMULA_ERROR: "FORMULA_ERROR",
    DISCOVER_BUTTON: "DISCOVER_BUTTON",
    EDIT_AREA: "EDIT_AREA",
    TASKS: "TASKS",
    NEW_DISCOVERY_POPUP_CONTENT: "NEW_DISCOVERY_POPUP_CONTENT",

    // MISSION_POPUP_GOAL: "MISSION_POPUP_GOAL",
    // MISSION_POPUP_CLOSE: "MISSION_POPUP_CLOSE",
    // REELS_COINS: "REELS_COINS",
    // SPIN_BUTTON: "SPIN_BUTTON",
    // INVENTORY_BUTTON: "INVENTORY_BUTTON",
    // ENCYCLOPEDIA_BUTTON: "ENCYCLOPEDIA_BUTTON",
    // SETTINGS_BUTTON: "SETTINGS_BUTTON",

    // ADD_SYMBOL_POPUP_TITLE: "ADD_SYMBOL_POPUP_TITLE",
    // ADD_SYMBOL_POPUP_SYMBOLS: "ADD_SYMBOL_POPUP_SYMBOLS",
    // ADD_SYMBOL_POPUP_SYMBOLS_REROLLS: "ADD_SYMBOL_POPUP_SYMBOLS_REROLLS",
    // ADD_SYMBOL_POPUP_FIRST_SYMBOL: "ADD_SYMBOL_POPUP_FIRST_SYMBOL",
    // ADD_SYMBOL_POPUP_FIRST_SYMBOL_VALUE: "ADD_SYMBOL_POPUP_FIRST_SYMBOL_VALUE",
    // ADD_SYMBOL_POPUP_FIRST_SYMBOL_DESC: "ADD_SYMBOL_POPUP_FIRST_SYMBOL_DESC",
    // ADD_SYMBOL_POPUP_CLOSE_BUTTON: "ADD_SYMBOL_POPUP_CLOSE_BUTTON",

    // MISSION_BONUS_POPUP_BONUSES: "MISSION_BONUS_POPUP_BONUSES",

    // // INVENTORY_POPUP_REMOVES: "INVENTORY_POPUP_REMOVES",
    // INVENTORY_POPUP_FIRST_SYMBOL: "INVENTORY_POPUP_FIRST_SYMBOL",
    // INVENTORY_POPUP_SYMBOL: "INVENTORY_POPUP_SYMBOL",
    // INVENTORY_POPUP_CLOSE: "INVENTORY_POPUP_CLOSE",

    // // INVENTORY_POPUP_FIRST_SYMBOL_REMOVE: "INVENTORY_POPUP_FIRST_SYMBOL_REMOVE"
    // COMPANION_INFO_POPUP_REMOVE: "COMPANION_INFO_POPUP_REMOVE",
    // COMPANION_INFO_POPUP_CLOSE: "COMPANION_INFO_POPUP_CLOSE",

    // CONFIG_INFO_POPUP_CLOSE: "CONFIG_INFO_POPUP_CLOSE",

    // ENCYCLOPEDIA_POPUP_SYMBOL: "ENCYCLOPEDIA_POPUP_SYMBOL",
    // ENCYCLOPEDIA_POPUP_CLOSE: "ENCYCLOPEDIA_POPUP_CLOSE",

    // SETTINGS_POPUP_CLOSE: "SETTINGS_POPUP_CLOSE",
    // SETTINGS_POPUP_SOUND: "SETTINGS_POPUP_SOUND",

    // GAME_OVER_POPUP_CLOSE: "GAME_OVER_POPUP_CLOSE",
}